//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudmvc4.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_student
    {

        public int Id { get; set; }

       
        [Required(ErrorMessage="Required")]

        public string Name { get; set; }
        [Required(ErrorMessage = "Required")]

        public string Fname { get; set; }
        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "Required")]

        [MinLength(10,ErrorMessage ="Mobile should be proper")]
        public string Mobile { get; set; }
        [Required(ErrorMessage = "Required")]

        public string Address { get; set; }
    }
}
